services:
  meshbridge:
    build: .
    env_file:
      - .env
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - "./:/app"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
